### ISSUE TITLE
Worn Equipment screenshot button becomes overlayed with inventory items and duplicates the screenshot option

### ISSUE THREAD

**Issue by BearsOnABus** [Blackberry0Pie/equipment-screenshot#10]
Not sure how to reproduce but happens to me pretty consistently where after playing normally for a bit the screenshot inventory button becomes a bunch of items in my inventory and when I right click I get many screenshot options.

![image](https://github.com/Blackberry0Pie/equipment-screenshot/assets/97892675/ea565d56-3819-423c-abc0-d75be34e8f07)

![image](https://github.com/Blackberry0Pie/equipment-screenshot/assets/97892675/77c3230e-ac06-4838-b5ea-cd84f07a35b6)

**Comment by BearsOnABus** [comment]
Found a way to reproduce. 

start as normal
![image](https://github.com/Blackberry0Pie/equipment-screenshot/assets/97892675/a61a7b15-3f65-4e80-9d65-5ef4d575be50)

Put any item in your inventory
![image](https://github.com/Blackberry0Pie/equipment-screenshot/assets/97892675/f7563f79-0320-4deb-be1f-0b30d76011ea)

Perform a teleport action from the inventory, teleport has to load a new area (for example, crafting guild teleport from the crafting guild will not cause an additional screenshot button to appear, but it will 'prime' additional buttons for when the next teleport to a new area occurs. ie. I am at crafting guild and teleport to crafting guild 3 times, still only one screenshot button. When I teleport to house I get 4 additional, 3 primed ones and one for the most recent teleport)
![image](https://github.com/Blackberry0Pie/equipment-screenshot/assets/97892675/667ea0b1-4813-428a-b87e-f1209f297d9f)

**Comment by Blackberry0Pie** [comment]
Working on it. Thank you for the reproduction information; it's been helpful.

**Comment by Nick2bad4u** [comment]
Im also having this issue:

![image](https://github.com/user-attachments/assets/d36e85d1-87e7-4c0d-999f-aecbfbc2a113)

I turned off other addons to make sure it was this one and it only appears when I re-enable "Equipment Screenshot"

**Comment by Blackberry0Pie** [comment]
I failed to find a solution to fix this. I will be pushing an update that removes the beautiful button. Future screenshot users will need to use the context-menu option on the equipment / inventory tab to screenshot.

**Comment by Nick2bad4u** [comment]
big sad :(
