### ISSUE TITLE
Combat Styles optional screenshot inclusion

### ISSUE THREAD

**Issue by robuhde** [Blackberry0Pie/equipment-screenshot#4]
Would be nice to have the option to also screenshot the combat styles menu. Autocast or out of the ordinary setups like DHL using crush on skeletal wyverns.

**Comment by Blackberry0Pie** [comment]
While this is technically possible, I'm not currently interested in adding this functionality. It's too niche, and honestly the autocast or attack style should be somewhat obvious from the context of the equipment, player, and target creature.
