### ISSUE TITLE
Some Equipment Stats options do not work?

### ISSUE THREAD

**Issue by robuhde** [Blackberry0Pie/equipment-screenshot#5]
"Show Atk/Def style icons", "Overlap Atk/Def stats on icons", "Show all 3 strength stats", "Write spellbook name", "Show Prayer and Weight", and "Show accurate weight" all seems to be defaulted to on with no ability to toggle them. Not sure if I'm missing something, but if so it is not clear what they change then.

**Comment by Blackberry0Pie** [comment]
Equipment Stats > Use all equipment stat options > uncheck
