### ISSUE TITLE
Blowpipe and Rune pouch settings

### ISSUE THREAD

**Issue by Vaquh** [Blackberry0Pie/equipment-screenshot#8]
The settings to show contents of the rune pouch and blowpipe, and as to be expected it does not work with the new divine rune pouch either.

I believe RuneLite changed how it keeps track of runes inside of a rune pouch, unsure if the same was done with blowpipe.

**Comment by Blackberry0Pie** [comment]
I believe I added this feature in the last update.

**Comment by hjdarnel** [comment]
I can also confirm that blowpipe settings are ignored. I can't seem to get the screenshot to show the contained scales/darts.

**Comment by Blackberry0Pie** [comment]
@hjdarnel The screenshot plugin tracks separately to any in-game overlay you might have. Have you tried right-click checking the blowpipe contents before taking the screenshot?

**Comment by Vaquh** [comment]
Problem is fixed, both blowpipe and divine rune pouch show contents in screenshot as expected.
